site_name: MkEn-ROADS

#site_dir: enroads_mkdocs
#docs_dir: docs

theme:
    name: readthedocs
    highlightjs: true

nav:
    - Home: index.md
    - User Guide:
        - Coal: parts/coal.md
        - Testing Area: parts/testing_area.md
    - About:
        - Release Notes: about/release-notes.md
        - Contributing: about/contributing.md
        - License: about/license.md

extra_javascript:
    - parts/mermaid.min.js
#    - https://cdnjs.cloudflare.com/ajax/libs/mermaid/7.1.0/mermaid.min.js
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML

extra_css:
    - parts/mermaid.css

#markdown_extensions:
#    - pymdownx.superfences:
#        custom_fences: [
#           {name: mermaid, class: mermaid}
#           ,{name: sequence, class: uml-sequence-diagram}
#        ]
